application: eve-combat-logs
version: 1-1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /index\.html
  static_files: static/index.html
  upload: static/index.html

- url: /parse_file
  script: parse_file.py

- url: /static/(.*)\.js
  static_files: static/\1.js
  upload: static/(.*)\.js

- url: /static/style.css
  static_files: static/style.css
  upload: static/style.css

skip_files:
- ^local
- ^README
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
