application: eve-combat-logs
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /index\.html
  static_files: static/index.html
  upload: static/index.html

- url: /parse_file
  script: parse_file.py

skip_files:
- ^local
- ^README
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
